<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\**" />
    <Content Remove="Contracts\**" />
    <EmbeddedResource Remove="Contracts\**" />
    <None Remove="Contracts\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Indt.Teste.ContratacaoService.Application\Indt.Teste.ContratacaoService.Application.csproj" />
    <ProjectReference Include="..\Indt.Teste.ContratacaoService.Infra\Indt.Teste.ContratacaoService.Infra.csproj" />
  </ItemGroup>

</Project>
