<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Indt.Teste.ContratacaoService.Domain\Indt.Teste.ContratacaoService.Domain.csproj" />
  </ItemGroup>

</Project>
